
import { GolferScore } from "@/types";

/**
 * Generate Masters Tournament leaderboard data based on provided results
 */
export function generateMastersLeaderboard(): GolferScore[] {
  const leaderboardData: GolferScore[] = [
    { position: 1, name: "Justin Rose", score: -8, today: -1, thru: "F" },
    { position: 2, name: "Bryson DeChambeau", score: -7, today: -4, thru: "F" },
    { position: 3, name: "Rory McIlroy", score: -6, today: -6, thru: "F" },
    { position: 3, name: "Corey Conners", score: -6, today: -2, thru: "F" },
    { position: 5, name: "Matt McCarty", score: -5, today: -4, thru: "F" },
    { position: 5, name: "Shane Lowry", score: -5, today: -4, thru: "F" },
    { position: 5, name: "Tyrrell Hatton", score: -5, today: -2, thru: "F" },
    { position: 5, name: "Scottie Scheffler", score: -5, today: -1, thru: "F" },
    { position: 9, name: "Rasmus Højgaard", score: -4, today: -5, thru: "F" },
    { position: 9, name: "Viktor Hovland", score: -4, today: -3, thru: "F" },
    { position: 9, name: "Jason Day", score: -4, today: -2, thru: "F" },
    { position: 12, name: "Hideki Matsuyama", score: -3, today: -4, thru: "F" },
    { position: 12, name: "Collin Morikawa", score: -3, today: -3, thru: "F" },
    { position: 12, name: "Sungjae Im", score: -3, today: -2, thru: "F" },
    { position: 12, name: "Patrick Reed", score: -3, today: -2, thru: "F" },
    { position: 12, name: "Ludvig Åberg", score: -3, today: 1, thru: "F" },
    { position: 17, name: "Xander Schauffele", score: -2, today: -3, thru: "F" },
    { position: 17, name: "Tommy Fleetwood", score: -2, today: -3, thru: "F" },
    { position: 17, name: "Davis Riley", score: -2, today: -3, thru: "F" },
    { position: 17, name: "Michael Kim", score: -2, today: -1, thru: "F" },
    { position: 17, name: "Brian Harman", score: -2, today: -1, thru: "F" },
    { position: 22, name: "Sam Burns", score: -1, today: -2, thru: "F" },
    { position: 22, name: "Nicolas Echavarria", score: -1, today: -2, thru: "F" },
    { position: 22, name: "Bubba Watson", score: -1, today: 0, thru: "F" },
    { position: 22, name: "Min Woo Lee", score: -1, today: 0, thru: "F" },
    { position: 22, name: "Harris English", score: -1, today: 1, thru: "F" },
    { position: 27, name: "Wyndham Clark", score: 0, today: -4, thru: "F" },
    { position: 27, name: "Max Homa", score: 0, today: -2, thru: "F" },
    { position: 27, name: "Nick Taylor", score: 0, today: -1, thru: "F" },
    { position: 27, name: "Justin Thomas", score: 0, today: -1, thru: "F" },
    { position: 27, name: "Tom Hoge", score: 0, today: 0, thru: "F" },
    { position: 27, name: "Sahith Theegala", score: 0, today: 0, thru: "F" },
    { position: 27, name: "Daniel Berger", score: 0, today: 1, thru: "F" },
    { position: 27, name: "Matt Fitzpatrick", score: 0, today: 1, thru: "F" },
    { position: 27, name: "Davis Thompson", score: 0, today: 1, thru: "F" },
    { position: 27, name: "Aaron Rai", score: 0, today: 2, thru: "F" },
    { position: 37, name: "Byeong Hun An", score: 1, today: -1, thru: "F" },
    { position: 37, name: "Brian Campbell", score: 1, today: 1, thru: "F" },
    { position: 37, name: "Maverick McNealy", score: 1, today: 1, thru: "F" },
    { position: 40, name: "Jon Rahm", score: 2, today: -1, thru: "F" },
    { position: 40, name: "Danny Willett", score: 2, today: -1, thru: "F" },
    { position: 40, name: "Charl Schwartzel", score: 2, today: 0, thru: "F" },
    { position: 40, name: "J.J. Spaun", score: 2, today: 0, thru: "F" },
    { position: 40, name: "Patrick Cantlay", score: 2, today: 0, thru: "F" },
    { position: 40, name: "J.T. Poston", score: 2, today: 0, thru: "F" },
    { position: 40, name: "Jordan Spieth", score: 2, today: 1, thru: "F" },
    { position: 40, name: "Tom Kim", score: 2, today: 1, thru: "F" },
    { position: 40, name: "Zach Johnson", score: 2, today: 2, thru: "F" },
    { position: 40, name: "Stephan Jaeger", score: 2, today: 2, thru: "F" },
    { position: 40, name: "Joaquín Niemann", score: 2, today: 2, thru: "F" },
    { position: 40, name: "Denny McCarthy", score: 2, today: 3, thru: "F" },
    { position: 40, name: "Max Greyserman", score: 2, today: 3, thru: "F" },
    { position: 40, name: "Akshay Bhatia", score: 2, today: 4, thru: "F" },
    // Cut players
    { position: 101, name: "Russell Henley", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Chris Kirk", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Dustin Johnson", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Bernhard Langer", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Keegan Bradley", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Justin Hastings (a)", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Joe Highsmith", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Rafael Campos", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Mike Weir", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Tony Finau", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Adam Schenk", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Sergio Garcia", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Fred Couples", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Sepp Straka", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Adam Scott", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Billy Horschel", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Phil Mickelson", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Brooks Koepka", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Cameron Smith", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Austin Eckroat", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Nicolai Højgaard", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Kevin Yu", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Jhonattan Vegas", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Robert MacIntyre", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Hiroshi Tai (a)", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "José María Olazábal", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Christiaan Bezuidenhout", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Cameron Young", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Patton Kizzire", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Lucas Glover", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Taylor Pendrith", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Will Zalatoris", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Thomas Detry", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Evan Beck (a)", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Cam Davis", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Matthieu Pavon", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Laurie Canter", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Jose Luis Ballester (a)", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Thriston Lawrence", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Noah Kent (a)", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Ángel Cabrera", score: 3, today: 0, thru: "F", status: "cut" },
    { position: 101, name: "Nick Dunlap", score: 3, today: 0, thru: "F", status: "cut" }
  ];

  return leaderboardData;
}
