// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adysmxbgiqhxouuanilv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkeXNteGJnaXFoeG91dWFuaWx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODA1NTUsImV4cCI6MjA1OTk1NjU1NX0.7O63puBf8tUn5EPplcmJLmqcEkvBsaas3FdN3s3aMaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);